### ISSUE TITLE
Vendor InSpec gem

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#112]
Instead of requiring Chef to install the InSpec gem, we vendor the gem into the cookbook. This allows users to update easier.
### Cookbook version

1.0.0

**Comment by jeremymv2** [comment]
@chris-rock 
The vendoring approach can be problematic for a couple of reasons that come to mind:
1. cookbook size - as of inspec 1.3.0 the size is 27MB of core libs + all deps
2. typically you'd manipulate ruby's $LOAD_PATH to prepend your custom vendor lib path from the cookbook; however, if certain gem libs are already present from Chef-client's lib path, the gem library from the chef-client install is ALWAYS used instead of the vendored one. This is because the chef-client already has the gem activated prior to loading/activating the one from the vendored path.

```
~/Downloads$ gem install --no-rdoc --no-ri --install-dir files/default/vendor --no-user-install inspec
...
...
~/Downloads$ du -sk files
27480	files  # 27MB
~/Downloads$
```

**Comment by chris-rock** [comment]
As discussed with @grdnrio @jeremymv2 @alexpop:

- We identified that at least 90% of the customers do not have their own gem repository
- for now, we added alternative gem source: https://github.com/chef-cookbooks/audit/pull/146
- If we are going to vendor, we should eliminate all non-required dependencies (eg. winrm or docker for train )

**Comment by chris-rock** [comment]
InSpec is part of Chef 13 now. Therefore we do not need to vendor inspec anymore.
