### ISSUE TITLE
way to ensure that the cookbook runs as last cookbook

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#13]

**Comment by chris-rock** [comment]
This work is currently tracked in https://github.com/chef/chef-rfc/blob/tm_ch/audit_phase/new/audit_phase.md

**Comment by spuder** [comment]
404

**Comment by chris-rock** [comment]
@spuder it is accepted now: https://github.com/chef/chef-rfc/blob/b96da1734d341a7a05d8bc92c82a9b75c94d197b/rfc083-audit-phase.md

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
