### ISSUE TITLE
inspec gem and dependencies

### ISSUE THREAD

**Issue by kmanohar1** [chef-cookbooks/audit#231]
I specified the following attributes in my role file:
  collector: 'chef-server' ,
  inspec_version: '1.8.0',
  inspec_gem_source: 'http://myserver/rubygems/'

and uploaded 'inspec gem' to my gem server. WHen the audit cookbook runs, it is running the following line of code:
 /opt/chef/embedded/bin/gem install inspec -q --no-rdoc --no-ri -v "1.8.0" --clear-sources --source=https://ocipd-sushi.gde.oraclecorp.com/ru                                        bygems/
ERROR:  Could not find a valid gem 'parallel' (~> 1.9) in any repository

I uploaded 'parallel' gem to my gem server but the dependency never ends. It keeps on asking for gems like sslshake, rubyzip etc. 

Is there a dependency list for installing 'inspec' gem? Or is there another easy way to install inspec gem?

**Comment by alexpop** [comment]
Hi there, you can see the list of dependencies for inspec 1.8.0 under RUNTIME DEPENDENCIES, here:

https://rubygems.org/gems/inspec/versions/1.8.0

**Comment by adamleff** [comment]
Hi @kmanohar1!

I think the easiest way to solve this would be to use bundler on your workstation to solve the dependencies and build a cache of the gems you need. Here's how to do it:

1. create an empty directory
2. Create a file called `Gemfile` which should contain the following:
```
source 'https://rubygems.org'
gem 'inspec', '= 1.8.0'
```
3. Run the command `bundle install --standalone`

In the `bundle/ruby/x.y.z/cache` directory (where `x.y.z` is your local version of Ruby) will be gem files for each of the solved dependencies. You can upload all of those to your gem mirror.

Also, I do want to point out that InSpec 1.8.0 is quite old... we're up to 1.26.0 at this point and there have been a LOT of bug fixes and feature enhancements/additions since 1.8. I'd strongly recommend upgrading when it's safe to do so.

**Comment by kmanohar1** [comment]
Thank you so much for a detailed description. Our Nodes does NOT have internet access. In this scenario, how do I solve this issue? We are planning on using our own gem server.

**Comment by adamleff** [comment]
@kmanohar1 In order to upload to your gem server, you're going to need to download the inspec gem and all its dependencies from the internet from at least one machine. I recommend you perform the steps I gave you earlier from a machine that has internet access, then take the resulting cached gems and move them into your local gem server. Once you do that, you'll be fine. But you HAVE to start from a machine with internet access first since that's where we publish InSpec.

**Comment by kekaichinose** [comment]
Thank you for tracking down this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities. We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
