### ISSUE TITLE
Move compliance server handling to inspec core

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#242]
### Cookbook version

4.0

### Issue

We have some code to handle login to Chef Compliance server. We should improve this to move https://github.com/chef-cookbooks/audit/blob/master/libraries/compliance.rb#L17-L63 completely to InSpec core and offer a stable interface in Inspec, so that the audit cookbook does not need to know which server and version it is talking to. This should all be covered within the compliance plugin in InSpec.

**Comment by kekaichinose** [comment]
Thank you for tracking down this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities. We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
