### ISSUE TITLE
 ERROR: Audit report was not generated properly, skipped reporting

### ISSUE THREAD

**Issue by siddhu07** [chef-cookbooks/audit#291]
### Cookbook version 5.0.3
[Version of the cookbook where you are encountering the issue]

### Actual Result: 
WARN: No audit tests are defined.
ERROR: Audit report was not generated properly, skipped reporting

Attributes/default.rb

default['audit']['reporter'] = ['chef-server-automate','json-file']
default['audit']['profiles'] = [
    {
      'name': 'InSpec Profile',
      'compliance': 'admin/cassandra'
    }
  ]

**Comment by adamleff** [comment]
@siddhu07 The error you're receiving indicates that there were no InSpec profiles configured to run so no report was generated. I'm afraid without any additional details, it's difficult to determine where the problem lies.

Can you please share additional information about how you configured the audit cookbook? What node attributes did you set?

**Comment by siddhu07** [comment]
@adamleff i have updated my question. i just downloaded audit cookbook from supermarket and tried to bootstrap. And i tried other way, just created a cookbook added "depends  audit" in metadata.rb and edited recipe, and tried to bootstrap.

**Comment by siddhu07** [comment]
thanks @adamleff , i got it. i bootstrapped with wrapper cookbook, deleted all dependencies and started from first.
