### ISSUE TITLE
Request: Ability to delete old nodes from Compliance or Automate without having to use API calls

### ISSUE THREAD

**Issue by MichaelMcClanahan** [chef-cookbooks/audit#306]
### Scenario:
Would like to be able to delete nodes from the Compliance or Automate server without having to resort to manually crafting API calls.

### Expected Result:
Enhance Audit cookbook to allow for the deletion of old nodes that no longer exist. Maybe a delete recipe?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
